config/routes.rb
QueueClassicAdmin::Engine.routes.draw do
  resources :queue_classic_scheduled_jobs do
    collection do
      delete :destroy_all
    end
  end

  resources :queue_classic_jobs do
    collection do
      delete :destroy_all
      put    :unlock_all
      post   :bulk_custom_action
    end

    member do
      post :unlock
      post :custom
      get  :show
    end
  end

  root to: "queue_classic_jobs#index"
end

app/models/queue_classic_admin/job_common.rb
require 'will_paginate'

module QueueClassicAdmin
  module JobCommon
    module ClassMethods
      KNOWN_COLUMN = ["id", "q_name", "method", "args", "locked_at", "created_at", "not_before", "locked_by", 'scheduled_at'].freeze
      SEARCHABLE_COLUMNS = [ :method, :args ].freeze

      def queue_counts
        group(:q_name).count
      end

      def extra_columns
        columns.map(&:name) - KNOWN_COLUMN
      end

      def searchable_columns
        @searchable_columns ||= SEARCHABLE_COLUMNS.dup
      end

      def search(query)
        sql = searchable_columns.map do |field|
          unless field == :args && args_is_json?
            "#{field} LIKE :query"
          end
        end.reject(&:nil?).join(" OR ")

        wildcard_query = ["%", query, "%"].join
        relation.where(sql, query: wildcard_query)
      end

      def args_is_json?
        type = self.type_for_attribute('args').type
        type.in?(%i(json jsonb))
      end
    end

    module InstanceMethods
      def arguments
        if self.class.args_is_json?
          args
        else
          MultiJson.decode(args)
        end
      end
    end

    def self.included(receiver)
      receiver.extend ClassMethods
      receiver.send :include, InstanceMethods
      receiver.attr_accessible :q_name unless defined?(ActionController::StrongParameters)
      receiver.per_page = 50 if receiver.respond_to?(:per_page)
    end
  end
end

app/models/queue_classic_admin/queue_classic_job.rb
module QueueClassicAdmin
  class QueueClassicJob < ActiveRecord::Base
    include JobCommon
    
    self.table_name = "queue_classic_jobs"

    scope :ready, -> { where("queue_classic_jobs.scheduled_at <= now()") }
    scope :scheduled, -> { where("queue_classic_jobs.scheduled_at > now()") }
  end
end

app/models/queue_classic_admin/stats.rb
module QueueClassicAdmin
  class Stats

    def running_job_count
      QueueClassicJob.where("locked_at IS NOT NULL").count
    end

  end
end

app/controllers/queue_classic_admin/application_controller.rb
module QueueClassicAdmin
  class ApplicationController < ActionController::Base
    protected
    def filter_jobs
      @queue_classic_jobs = QueueClassicJob.order("id DESC")

      if self.class == QueueClassicScheduledJobsController
        @scoped_jobs = QueueClassicJob.scheduled
        @queue_classic_jobs = @queue_classic_jobs.scheduled
      else
        @scoped_jobs = QueueClassicJob.ready
        @queue_classic_jobs = @queue_classic_jobs.ready
      end

      if params[:q_name].present?
        @queue_classic_jobs = @queue_classic_jobs.where(q_name: params[:q_name])
      end
      if params[:search].present?
        @queue_classic_jobs = @queue_classic_jobs.search(params[:search])
      end
      if params[:sort].present?
        @queue_classic_jobs = @queue_classic_jobs.reorder("#{params[:sort]} #{params[:dir]} NULLS LAST")
      end
      @queue_classic_jobs
    end
  end
end

app/controllers/queue_classic_admin/queue_classic_jobs_controller.rb
require_dependency "queue_classic_admin/application_controller"

module QueueClassicAdmin
  class QueueClassicJobsController < ApplicationController
    before_action :get_job, only: [:destroy, :unlock, :custom, :show]
    before_action :filter_jobs, only: [:index, :destroy_all, :unlock_all, :bulk_custom_action]
    def index
      @queue_classic_jobs = @queue_classic_jobs.paginate(page: params[:page])
    end

    def destroy
      @queue_classic_job.destroy
      redirect_back fallback_location: {action: :index}
    end

    def destroy_all
      @queue_classic_jobs.delete_all
      redirect_to queue_classic_jobs_url
    end

    def unlock_all
      @queue_classic_jobs.where('locked_at < ?', 5.minutes.ago).update_all(locked_at: nil)
      redirect_to queue_classic_jobs_url
    end

    def bulk_custom_action
      custom_action = QueueClassicAdmin.custom_bulk_actions[params[:custom_action]]
      custom_action.action.call(@queue_classic_jobs)

      redirect_to queue_classic_jobs_url
    end

    def unlock
      @queue_classic_job.locked_at = nil
      @queue_classic_job.save
      redirect_back fallback_location: {action: :index}
    end

    def show
      query = "SELECT * FROM pg_catalog.pg_locks lock JOIN pg_catalog.pg_stat_activity stat ON lock.pid = stat.pid WHERE lock.pid = #{@queue_classic_job.locked_by.to_i}"
      @locks = QueueClassicJob.connection.execute(query)
    end

    def custom
      custom_action = QueueClassicAdmin.custom_actions[params[:custom_action]]
      custom_action.action.call(@queue_classic_job)
      redirect_back fallback_location: {action: :index}
    end

    private
    def index_path(*params)
      queue_classic_jobs_path(*params)
    end

    def get_job
      @queue_classic_job = QueueClassicJob.find(params[:id])
    end

    def scheduled?
      false
    end

    helper_method :index_path
    helper_method :scheduled?
  end
end

app/controllers/queue_classic_admin/queue_classic_scheduled_jobs_controller.rb
require_dependency "queue_classic_admin/application_controller"

module QueueClassicAdmin
  class QueueClassicScheduledJobsController < ApplicationController
    before_action :filter_jobs, only: %i(index destroy_all)

    def index
    end

    def destroy
      @queue_classic_scheduled_job = QueueClassicJob.find(params[:id])
      @queue_classic_scheduled_job.destroy
      redirect_to queue_classic_scheduled_jobs_url
    end

    def destroy_all
      @queue_classic_jobs.delete_all
      redirect_to queue_classic_jobs_url
    end

    private

    def index_path(*params)
      queue_classic_scheduled_jobs_path(*params)
    end

    def scheduled?
      true
    end

    helper_method :index_path
    helper_method :scheduled?
  end
end

app/helpers/queue_classic_admin/application_helper.rb
module QueueClassicAdmin
  module ApplicationHelper
    def sortable_column(name, title)
      opts = {sort: name}
      opts[:dir] = (params[:dir] == "asc" ? "desc" : "asc")
      content_tag :th do
        s = link_to title, params.merge(opts).permit
        if params[:sort] == name.to_s
          icon = if params[:dir] == 'asc'
            "&uarr;"
          else
            "&darr;"
          end
          s += raw(icon)
        end
        s.html_safe
      end
    end
  end
end

app/views/layouts/queue_classic_admin/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= content_for?(:title) ? yield(:title) : "Queue Classic" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "queue_classic_admin/application", media: "all" %>
    <%= javascript_include_tag "queue_classic_admin/application" %>
  </head>
  <body>

    <nav class="navbar navbar-dark bg-inverse">
      <%= link_to "Queue Classic Admin", queue_classic_jobs_path, class: "navbar-brand" %>
      <ul class="nav navbar-nav">
        <li class="nav-item"><%= link_to "Jobs", queue_classic_jobs_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Scheduled Jobs", queue_classic_scheduled_jobs_path, class: "nav-link" %></li>
      </ul>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/queue_classic_admin/queue_classic_jobs/index.html.erb
<h1>Jobs</h1>

<ul class="nav nav-pills">
  <li class="<%= q_name_pill_class(nil)%>" >
    <a href="<%= queue_classic_jobs_path %>"><%= "All (#{QueueClassicAdmin::QueueClassicJob.count})" %></a>
  </li>
  <% QueueClassicAdmin::QueueClassicJob.queue_counts.each do |q_name, count| %>
    <li class="<%= q_name_pill_class(q_name) %>">
    <a href="<%= queue_classic_jobs_path(q_name: q_name) %>"><%= "#{q_name} (#{count})" %></a>
    </li>
  <% end %>
</ul>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Queue</th>
      <th>Method</th>
      <th>Arguments</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @queue_classic_jobs.each do |queue_classic_job| %>
    <tr>
      <td><%= queue_classic_job.q_name  %></td>
      <td><%= queue_classic_job.method  %></td>
      <td><%= queue_classic_job.arguments.inspect%></td>
      <td><%= link_to 'Destroy', queue_classic_job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br />

app/views/queue_classic_admin/queue_classic_jobs/show.html.erb
<h1>Details for job #<%= @queue_classic_job.id %></h1>

<table class="table table-bordered table-hover">
  <% @queue_classic_job.attributes.each do |attr, value| %>
    <tr>
      <td><strong><%= attr %></strong></td>
      <td><strong><%= value %></strong></td>
    </tr>
  <% end %>
</table>

<h2>Locks</h2>
<% if @locks.count == 0 %>
  There are no locks related.
<% end %>
<% @locks.each do |lock| %>
  <hr>
  <%= lock %>
<% end %>

app/views/queue_classic_admin/queue_classic_scheduled_jobs/index.html.erb
<h1>Scheduled Jobs</h1>

<%= render "queue_classic_admin/shared/job_list" %>

app/views/queue_classic_admin/shared/_job_list.html.erb
<div id="search">
  <%= form_tag(url_for(params.permit!), method: 'GET') do %>
    <%= hidden_field_tag :q_name, params[:q_name] %>
    <input class="search-query" name="search" placeholder="Search jobs" value="<%= params[:search] %>"/>
  <% end %>
</div>

<ul class="nav nav-pills">
  <li class="<%= q_name_pill_class(nil)%>" >
    <a href="<%= index_path %>"><%= "All (#{@scoped_jobs.count})" %></a>
  </li>

  <% @scoped_jobs.queue_counts.each do |q_name, count| %>
    <li class="<%= q_name_pill_class(q_name) %>">
    <a href="<%= index_path(q_name: q_name) %>"><%= "#{q_name} (#{count})" %></a>
    </li>
  <% end %>
</ul>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <%= sortable_column :q_name, "Queue" %>
      <%= sortable_column :id, "ID" %>
      <%= sortable_column :created_at, "Enqueued At" %>
      <%= sortable_column :locked_at, "Locked At" %>
      <%= sortable_column :locked_by, "Locked By" %>
      <%= sortable_column :method, "Method" %>
      <%= sortable_column :args, "Arguments" %>
      <% if QueueClassicAdmin::QueueClassicJob.columns_hash['not_before'] %>
        <th>Run At</th>
      <% end %>
      <% QueueClassicAdmin::QueueClassicJob.extra_columns.each do |column| %>
        <%= sortable_column column, column.titleize %>
      <% end %>
      <th>
        <%=
          link_to "Destroy Matching", url_for(params.merge(action: 'destroy_all')), class: 'btn btn-danger', data: {confirm: "Are you sure?", method: :delete}
        %>
        <% unless scheduled? %>
          <%=
            link_to "Unlock Matching > 5 mins", url_for(params.merge(action: 'unlock_all')), class: 'btn btn-danger', data: {confirm: "Are you sure?", method: :put}
          %>
        <% end %>
        <% QueueClassicAdmin.custom_bulk_actions.each do |slug, action| %>
          <%= link_to action.name, bulk_custom_action_queue_classic_jobs_path(params.merge(custom_action: slug)), class: 'btn btn-danger', data: {confirm: "Are you sure?", method: :post} %>
        <% end %>
      </th>
    </tr>
  </thead>

  <tbody>
  <% @queue_classic_jobs.each do |queue_classic_job| %>
    <tr>
      <td><%= queue_classic_job.q_name  %></td>
      <td><%= link_to queue_classic_job.id, queue_classic_job  %></td>
      <td>
        <% if queue_classic_job.respond_to?(:created_at) %>
          <%= time_ago_in_words queue_classic_job.created_at %>
          <br/>
          <small>
            (<%= queue_classic_job.created_at %>)
          </small>
        <% else %>
          &mdash;
        <% end %>
      </td>
      <td>
        <% if queue_classic_job[:locked_at].nil? %>
          &mdash;
        <% else %>
          <%= time_ago_in_words queue_classic_job.locked_at %>
          <br/>
          <small>
            (<%= queue_classic_job.locked_at %>)
          </small>
        <% end %>
      </td>
      <td>
        <%= queue_classic_job[:locked_by] %>
      </td>
      <td><%= queue_classic_job.method  %></td>
      <td><%= queue_classic_job.arguments.inspect%></td>
      <% if QueueClassicAdmin::QueueClassicJob.columns_hash['not_before'] %>
        <td><%= queue_classic_job.not_before %></td>
      <% end %>

      <% QueueClassicAdmin::QueueClassicJob.extra_columns.each do |column| %>
        <td><%= queue_classic_job[column] %></th>
      <% end %>

      <td>
        <%= link_to 'Details', queue_classic_job_path(queue_classic_job), class: 'btn btn-info' %>
        <%= link_to 'Destroy', queue_classic_job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <% if queue_classic_job[:locked_at] %>
          <%= link_to 'Unlock', unlock_queue_classic_job_path(queue_classic_job), method: :post, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <% end %>

        <% QueueClassicAdmin.custom_actions.each do |slug, action| %>
          <%= link_to action.name, custom_queue_classic_job_path(queue_classic_job, custom_action: slug), method: :post, class: "btn btn-danger" %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @queue_classic_jobs, renderer: BootstrapPagination::Rails %>

<br />